---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: 了解 NetApp Console 本地部署中功能和数据服务的最新更改。 
---
= NetApp Console 本地部署的最新变化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解 NetApp Console 本地部署中功能和数据服务的最新更改。



[[17-august-2026]]
== 2026年8月17日



[[backup-and-recovery]]
=== 备份和恢复



==== Hyper-V 工作负载增强功能

在此版本中，Hyper-V 工作负载引入了以下增强功能：

*将对象存储备份还原到备用位置*：您现在可以将 Hyper-V 虚拟机、文件和文件夹从对象存储还原到备用存储位置。

有关保护 Hyper-V 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保护 Hyper-V 工作负载"]。



==== Kubernetes 工作负载增强功能

在此版本中，Kubernetes 工作负载引入了以下增强功能：

* *Trident Protect 26.08*：此版本包括 Trident Protect 26.08。
* *备份重试*：您现在可以启用备份重试，并将重试次数和重试间隔配置为 Kubernetes 保护策略中的高级设置。
* *部分备份成功*：您现在可以在 Kubernetes 保护策略中配置高级设置，以便在个别资源出现故障时继续备份，从而允许备份作业以部分成功的状态完成。即使某些资源在备份操作期间失败，您也可以还原已备份的资源。
* *崩溃一致性和虚拟机一致性备份*：Backup and Recovery for NetApp Console 服务现在支持配置保护策略，以创建崩溃一致性或虚拟机一致性备份或快照。您还可以自定义在保护操作期间执行虚拟机冻结的方式。
* *Reconnect Kubernetes cluster upon Console agent IP change*：Backup and Recovery for NetApp Console 服务现在支持在代理的 IP 地址发生变化时，将集群重新连接到其 Console 代理。
* *将集群迁移到新的 Console 代理*：Backup and Recovery for NetApp Console 服务现在支持在原始代理失败或被删除时将集群迁移到新的 Console 代理，从而确保应用保护不中断。


要了解有关保护 Kubernetes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["了解如何通过 NetApp Backup and Recovery 保护 Kubernetes 工作负载"]。



==== Oracle Database 工作负载增强

在此版本中，Oracle 数据库工作负载引入了以下增强功能：

* *Pluggable Database (PDB) restore*：您现在可以还原单个可插拔数据库 (PDB) 和 PDB 表空间，包括时间点恢复。
* *Pluggable Database (PDB) clone*：您现在可以将单个 PDB 克隆到现有的目标容器数据库 (CDB) 中，并且可以选择在克隆完整的容器数据库时排除 PDB。


要了解有关保护 Oracle Database 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保护 Oracle 数据库工作负载"]。



[[10-august-2026]]
== 2026年8月10日



[[netapp-console-local-deployment]]
=== NetApp Console 本地部署



==== 介绍 NetApp Console 本地部署

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["了解 NetApp Console 本地部署"]。



[[backup-and-recovery]]
=== 备份和恢复



==== 常规 NetApp Backup and Recovery 增强功能

* *支持 NetApp Console 本地部署*：此版本的 NetApp Backup and Recovery 支持处于预览状态的 NetApp Console 本地部署。
* *90 天的作业保留*：Backup and Recovery 现在会在 Job Monitor 中保留作业信息 90 天。




==== VMware 工作负载增强功能

在此版本中，VMware 工作负载引入了以下增强功能：

* *还原到备用位置支持（适用于 SAN VM）*：现在，您可以将基于 SAN 的 VM 备份还原到备用位置。
* *Multiple backup delete support*：您现在可以一次删除多个备份。


要了解有关保护 VMware 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保护 VMware 工作负载概述"]。



==== Kubernetes 工作负载增强功能

在此版本中，Kubernetes 工作负载引入了以下增强功能：

* *预览对气隙资源的支持*：如果在 NetApp Console 本地部署中运行 NetApp Backup and Recovery，您可以发现、保护和还原气隙 Kubernetes 资源。此功能在此版本中处于预览状态。


要了解有关保护 Kubernetes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保护 Kubernetes 工作负载概述"]。



==== ONTAP Volumes 工作负载增强

在此版本中，ONTAP Volumes 工作负载引入了以下增强功能：

* *将还原作业优先于备份*：现在，在还原虚拟机或文件时，您可以将还原作业优先于备份作业。
* *在不激活 Backup and Recovery 的情况下发现 ONTAP 系统和卷*：您现在可以在不激活 Backup and Recovery 的情况下发现系统和卷。


要了解有关保护 ONTAP Volumes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["保护 ONTAP 卷工作负载概述"]。



[[13-july-2026]]
== 2026年7月13日



[[backup-and-recovery]]
=== 备份和恢复



==== 增强对所有工作负载的多存储桶支持

NetApp Backup and Recovery 现在支持使用跨不同云提供商的多达 100 个存储桶来保护系统中的工作负载。ONTAP 9.19.1 或更高版本需要支持每个系统超过 6 个存储桶。

要了解有关 NetApp Backup and Recovery 的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["了解 NetApp Backup and Recovery"]。



[[15-june-2026]]
== 2026 年 6 月 15 日



[[backup-and-recovery]]
=== 备份和恢复



==== Kubernetes 工作负载增强功能

在此版本中，Kubernetes 工作负载引入了以下增强功能：

* *Trident Protect 26.06*：此版本包括 Trident Protect 26.06。
* *在还原期间跳过应用程序创建*：现在，您可以在还原操作期间跳过自动创建应用程序自定义资源对象。这减少了应用程序清单中不必要的条目。
* *还原虚拟机永久卷声明*：现在，在还原基于虚拟机的应用程序时，您可以还原单个永久卷声明，而无需还原整个虚拟机，从而在特定磁盘或卷受损坏或数据丢失影响时加快恢复速度。
* *作业监视器改进*：作业监控现在提供了对 Kubernetes 保护作业的增强可见性。您可以查看有关作业和子作业的详细状态信息，并查看每个作业和子作业使用的目标存储。


要了解有关保护 Kubernetes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保护 Kubernetes 工作负载概述"]。



[[08-june-2026]]
== 2026 年 6 月 08 日



[[backup-and-recovery]]
=== 备份和恢复



==== ONTAP Volumes 工作负载增强

在此版本中，ONTAP Volumes 工作负载引入了以下增强功能：

*支持 S3 兼容云存储*：卷工作负载的 NetApp Backup and Recovery 现在支持备份到 S3 兼容云存储。

要了解有关保护 ONTAP Volumes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["保护 ONTAP 卷工作负载概述"]。



==== Hyper-V 工作负载增强功能

在此版本中，Hyper-V 工作负载引入了以下增强功能：

* *将文件和文件夹还原到来宾 VM 改进*：您现在可以将文件和文件夹从主存储或二级存储上的快照还原到来宾 Windows VM。CIFS 和 SAN VM 现在支持此功能。
* *保护组现在使用主机时区计划*：保护组现在使用 Hyper-V 主机的时区。在引入主机时区调度之前创建的保护组继续使用其先前配置的时间（通常为 UTC）。要更新这些保护组以使用 Hyper-V 主机时区，必须重新创建计划。有关详细信息，请参见 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["创建和管理 Hyper-V 工作负载的保护组"]。


有关保护 Hyper-V 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["使用 NetApp Backup and Recovery 的 Hyper-V 保护工作流"]。



==== VMware 工作负载增强功能

在此版本中，VMware 工作负载引入了以下增强功能：

* *保护组现在使用主机时区计划*：保护组现在使用托管 VMware vCenter Server 的时区。在引入主机时区计划之前创建的保护组继续在其先前配置的时区（通常为 UTC）上运行。要使用 vCenter 时区，必须重新创建计划。有关详细信息，请参见 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["创建和管理 VMware 工作负载的保护组"]。


要了解有关保护 VMware 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保护 VMware 工作负载概述"]。
