---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: 了解 NetApp Console 本地部署中功能和数据服务的最新更改。 
---
= NetApp Console 本地部署的最新变化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解 NetApp Console 本地部署中功能和数据服务的最新更改。



[[21-september-2026]]
== 2026年9月21日



[[backup-and-recovery]]
=== 备份和恢复



==== Kubernetes 工作负载增强功能

在此版本中，Kubernetes 工作负载引入了以下增强功能：

* *Trident Protect 26.09*：此版本包括 Trident Protect 26.09。
* *集群和命名空间粒度的基于角色的访问控制*：在 Kubernetes 集群发现期间，您可以通过选择要与新集群关联的项目或文件夹来控制对资源的访问。您还可以注册特定命名空间以进行访问控制。这可以在集群或命名空间级别实现更精细的访问控制。
* *Restore files and folders*：现在，您可以从基于 Kubernetes VM 的应用程序备份中还原或下载特定的文件和文件夹。


要了解有关保护 Kubernetes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["了解如何通过 NetApp Backup and Recovery 保护 Kubernetes 工作负载"]。



[[16-september-2026]]
== 2026年9月16日



[[backup-and-recovery]]
=== 备份和恢复



==== 常规 NetApp Backup and Recovery 增强功能

在此版本中，KVM、Hyper-V 和 VMware 工作负载引入了以下增强功能：

*在虚拟机主机发现期间进行凭据选择* ：现在，当您发现 KVM、Hyper-V 或 VMware 主机时，您可以使用已添加到 Backup and Recovery 中的凭据。



==== Hyper-V 工作负载增强

在此版本中，Hyper-V 工作负载引入了以下增强功能：

*虚拟机跨磁盘保护*：对于 CIFS 配置，Backup and Recovery 现在支持保护组中连接到每个虚拟机的每个磁盘。这包括分布在多个 ONTAP 卷或 ONTAP 存储系统（跨磁盘）上的文件，以及仅限于单个位置的文件。

有关保护 Hyper-V 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保护 Hyper-V 工作负载"]。



==== ONTAP Volumes 工作负载增强

在此版本中，ONTAP Volumes 工作负载引入了以下预览增强功能：

*每日备份数据传输报告*：NetApp Backup and Recovery for Volumes 现在在"报告"选项卡下提供每日备份数据传输报告，让您可以查看整个环境中的每日备份和复制数据传输活动。您可以生成完整帐户或选定存储系统的报告，按日期范围和保护类型进行筛选，并以 CSV 格式下载结果。

要了解有关保护 ONTAP Volumes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["了解使用 NetApp Backup and Recovery 的 ONTAP 卷保护"]。



[[17-august-2026]]
== 2026年8月17日



[[backup-and-recovery]]
=== 备份和恢复



==== Hyper-V 工作负载增强功能

在此版本中，Hyper-V 工作负载引入了以下增强功能：

*将对象存储备份还原到备用位置*：您现在可以将 Hyper-V 虚拟机、文件和文件夹从对象存储还原到备用存储位置。

有关保护 Hyper-V 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保护 Hyper-V 工作负载"]。



==== Kubernetes 工作负载增强功能

在此版本中，Kubernetes 工作负载引入了以下增强功能：

* *Trident Protect 26.08*：此版本包括 Trident Protect 26.08。
* *备份重试*：您现在可以启用备份重试，并将重试次数和重试间隔配置为 Kubernetes 保护策略中的高级设置。
* *部分备份成功*：您现在可以在 Kubernetes 保护策略中配置高级设置，以便在个别资源出现故障时继续备份，从而允许备份作业以部分成功的状态完成。即使某些资源在备份操作期间失败，您也可以还原已备份的资源。
* *崩溃一致性和虚拟机一致性备份*：Backup and Recovery for NetApp Console 服务现在支持配置保护策略，以创建崩溃一致性或虚拟机一致性备份或快照。您还可以自定义在保护操作期间执行虚拟机冻结的方式。
* *Reconnect Kubernetes cluster upon Console agent IP change*：Backup and Recovery for NetApp Console 服务现在支持在代理的 IP 地址发生变化时，将集群重新连接到其 Console 代理。
* *将集群迁移到新的 Console 代理*：Backup and Recovery for NetApp Console 服务现在支持在原始代理失败或被删除时将集群迁移到新的 Console 代理，从而确保应用保护不中断。


要了解有关保护 Kubernetes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["了解如何通过 NetApp Backup and Recovery 保护 Kubernetes 工作负载"]。



==== Oracle Database 工作负载增强

在此版本中，Oracle 数据库工作负载引入了以下增强功能：

* *Pluggable Database (PDB) restore*：您现在可以还原单个可插拔数据库 (PDB) 和 PDB 表空间，包括时间点恢复。
* *Pluggable Database (PDB) clone*：您现在可以将单个 PDB 克隆到现有的目标容器数据库 (CDB) 中，并且可以选择在克隆完整的容器数据库时排除 PDB。


要了解有关保护 Oracle Database 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["了解如何使用 NetApp Backup and Recovery 保护 Oracle 数据库工作负载"]。



[[10-august-2026]]
== 2026年8月10日



[[netapp-console-local-deployment]]
=== NetApp Console 本地部署



==== 介绍 NetApp Console 本地部署

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["了解 NetApp Console 本地部署"]。

https://docs.netapp.com/us-en/console-local/console-differences.html["了解 NetApp Console 本地部署与 NetApp Console SaaS 和私有模式之间的区别"]。



[[backup-and-recovery]]
=== 备份和恢复



==== 常规 NetApp Backup and Recovery 增强功能

* *支持 NetApp Console 本地部署*：此版本的 NetApp Backup and Recovery 支持处于预览状态的 NetApp Console 本地部署。
* *90 天的作业保留*：Backup and Recovery 现在会在 Job Monitor 中保留作业信息 90 天。




==== VMware 工作负载增强功能

在此版本中，VMware 工作负载引入了以下增强功能：

* *还原到备用位置支持（适用于 SAN VM）*：现在，您可以将基于 SAN 的 VM 备份还原到备用位置。
* *Multiple backup delete support*：您现在可以一次删除多个备份。


要了解有关保护 VMware 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保护 VMware 工作负载概述"]。



==== Kubernetes 工作负载增强功能

在此版本中，Kubernetes 工作负载引入了以下增强功能：

* *预览对气隙资源的支持*：如果在 NetApp Console 本地部署中运行 NetApp Backup and Recovery，您可以发现、保护和还原气隙 Kubernetes 资源。此功能在此版本中处于预览状态。


要了解有关保护 Kubernetes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保护 Kubernetes 工作负载概述"]。



==== ONTAP Volumes 工作负载增强

在此版本中，ONTAP Volumes 工作负载引入了以下增强功能：

* *将还原作业优先于备份*：现在，在还原虚拟机或文件时，您可以将还原作业优先于备份作业。
* *在不激活 Backup and Recovery 的情况下发现 ONTAP 系统和卷*：您现在可以在不激活 Backup and Recovery 的情况下发现系统和卷。


要了解有关保护 ONTAP Volumes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["保护 ONTAP 卷工作负载概述"]。



[[13-july-2026]]
== 2026年7月13日



[[backup-and-recovery]]
=== 备份和恢复



==== 增强对所有工作负载的多存储桶支持

NetApp Backup and Recovery 现在支持使用跨不同云提供商的多达 100 个存储桶来保护系统中的工作负载。ONTAP 9.19.1 或更高版本需要支持每个系统超过 6 个存储桶。

要了解有关 NetApp Backup and Recovery 的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["了解 NetApp Backup and Recovery"]。
